spring.application.name=task-management-system
spring.config.import=optional:file:.env[.properties]
#----------------------------------------------------------------------------------#
#Database Connection Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#----------------------------------------------------------------------------------#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#----------------------------------------------------------------------------------#
Jwt.secret.key=${JWT_SECRET}
#----------------------------------------------------------------------------------#
# (1000*60*5)= 5 minutes
jwt.expiration.access-token=${JWT_ACCESS}
jwt.expiration.refresh-token=${JWT_REFRESHMENT_DAYS}
#----------------------------------------------------------------------------------#
# SMTP server settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
#----------------------------------------------------------------------------------#
# Additional email properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#----------------------------------------------------------------------------------#
#Scalar
scalar.enabled=true
# Optional: Custom path (default: /scalar)
scalar.path=/docs
# The URL of your OpenAPI document
scalar.url=http://localhost:8080/v3/api-docs
#----------------------------------------------------------------------------------#
#OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
#spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
#spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
#spring.security.oauth2.client.registration.github.scope=user:email


